f = open('src/views/NodeEditor.vue', 'a', encoding='utf-8')
f.write('\n<script setup>\n')
f.write('import { ref } from "vue"\n')
f.write('import { ElMessage } from "element-plus"\n')
f.write('import { Close } from "@element-plus/icons-vue"\n')
f.write('\nconst nodes = ref([])\n')
f.write('const connections = ref([])\n')
f.write('const selectedNode = ref(null)\n')
f.write('const connectMode = ref(false)\n')
f.write('const firstPort = ref(null)\n')
f.write('let dragNode = null\n')
f.write('let dragOffset = { x: 0, y: 0 }\n')
f.write('\nconst nodeTypes = {\n')
f.write('  symptom: { title: "症状输入", color: "#409eff" },\n')
f.write('  prescription: { title: "方剂库", color: "#67c23a" },\n')
f.write('  rule: { title: "配伍规则", color: "#e6a23c" },\n')
f.write('  output: { title: "输出节点", color: "#f56c6c" }\n')
f.write('}\n')
f.write('\nlet nodeIdCounter = 1\n')
f.write('let connIdCounter = 1\n')
f.write('\nfunction getNodeTitle(type) {\n')
f.write('  return nodeTypes[type]?.title || type\n')
f.write('}\n')
f.write('\nfunction addNode(type) {\n')
f.write('  const node = {\n')
f.write('    id: "node-" + nodeIdCounter++,\n')
f.write('    type,\n')
f.write('    x: 100 + Math.random() * 400,\n')
f.write('    y: 100 + Math.random() * 300,\n')
f.write('    data: { symptoms: [], prescription: "", rules: [], result: null }\n')
f.write('  }\n')
f.write('  nodes.value.push(node)\n')
f.write('  ElMessage.success("已添加 " + getNodeTitle(type) + " 节点")\n')
f.write('}\n')
f.write('\nfunction deleteNode(nodeId) {\n')
f.write('  connections.value = connections.value.filter(c => c.from !== nodeId && c.to !== nodeId)\n')
f.write('  nodes.value = nodes.value.filter(n => n.id !== nodeId)\n')
f.write('  if (selectedNode.value === nodeId) selectedNode.value = null\n')
f.write('  ElMessage.info("节点已删除")\n')
f.write('}\n')
f.write('\nfunction startDrag(node, event) {\n')
f.write('  selectedNode.value = node.id\n')
f.write('  dragNode = node\n')
f.write('  dragOffset = { x: event.clientX - node.x, y: event.clientY - node.y }\n')
f.write('  document.addEventListener("mousemove", onDrag)\n')
f.write('  document.addEventListener("mouseup", stopDrag)\n')
f.write('}\n')
f.write('\nfunction onDrag(event) {\n')
f.write('  if (!dragNode) return\n')
f.write('  dragNode.x = event.clientX - dragOffset.x\n')
f.write('  dragNode.y = event.clientY - dragOffset.y\n')
f.write('}\n')
f.write('\nfunction stopDrag() {\n')
f.write('  dragNode = null\n')
f.write('  document.removeEventListener("mousemove", onDrag)\n')
f.write('  document.removeEventListener("mouseup", stopDrag)\n')
f.write('}\n')
f.write('\nfunction handleCanvasClick() {\n')
f.write('  selectedNode.value = null\n')
f.write('}\n')
f.write('\nfunction toggleConnectMode() {\n')
f.write('  connectMode.value = !connectMode.value\n')
f.write('  firstPort.value = null\n')
f.write('  if (connectMode.value) ElMessage.info("已进入连线模式")\n')
f.write('}\n')
f.write('\nfunction handlePortClick(portType, node) {\n')
f.write('  if (connectMode.value) {\n')
f.write('    if (!firstPort.value) {\n')
f.write('      firstPort.value = { portType, node }\n')
f.write('    } else {\n')
f.write('      if (firstPort.value.portType === "out" && portType === "in" && firstPort.value.node.id !== node.id) {\n')
f.write('        const exists = connections.value.some(c => c.from === firstPort.value.node.id && c.to === node.id)\n')
f.write('        if (!exists) {\n')
f.write('          connections.value.push({ id: "conn-" + connIdCounter++, from: firstPort.value.node.id, to: node.id })\n')
f.write('          ElMessage.success("连线成功")\n')
f.write('        }\n')
f.write('      }\n')
f.write('      firstPort.value = null\n')
f.write('    }\n')
f.write('  }\n')
f.write('}\n')
f.write('\nfunction deleteConnection(connId) {\n')
f.write('  connections.value = connections.value.filter(c => c.id !== connId)\n')
f.write('  ElMessage.info("连线已删除")\n')
f.write('}\n')
f.write('\nfunction getConnectionPath(conn) {\n')
f.write('  const fromNode = nodes.value.find(n => n.id === conn.from)\n')
f.write('  const toNode = nodes.value.find(n => n.id === conn.to)\n')
f.write('  if (!fromNode || !toNode) return ""\n')
f.write('  const fromX = fromNode.x + 200\n')
f.write('  const fromY = fromNode.y + 40\n')
f.write('  const toX = toNode.x\n')
f.write('  const toY = toNode.y + 40\n')
f.write('  const midX = (fromX + toX) / 2\n')
f.write('  return "M " + fromX + " " + fromY + " C " + midX + " " + fromY + ", " + midX + " " + toY + ", " + toX + " " + toY\n')
f.write('}\n')
f.write('\nfunction clearAll() {\n')
f.write('  nodes.value = []\n')
f.write('  connections.value = []\n')
f.write('  selectedNode.value = null\n')
f.write('  connectMode.value = false\n')
f.write('  ElMessage.info("已清空")\n')
f.write('}\n')
f.write('\nfunction runFlow() {\n')
f.write('  const outputNodes = nodes.value.filter(n => n.type === "output")\n')
f.write('  if (outputNodes.length === 0) {\n')
f.write('    ElMessage.warning("请添加输出节点")\n')
f.write('    return\n')
f.write('  }\n')
f.write('  const mockResults = [{ name: "降气平哮方", score: 95 }, { name: "定喘汤", score: 88 }, { name: "小青龙汤", score: 82 }, { name: "苏子降气汤", score: 78 }]\n')
f.write('  outputNodes.forEach(node => { node.data.result = mockResults.slice(0, 4) })\n')
f.write('  ElMessage.success("运行完成")\n')
f.write('}\n')
f.write('</script>\n')
f.close()
print('Done')