import
os
f = open('src/components/MouseTrail.vue','w',encoding='utf-8')
f.write("<template><canvas v-show=\"enabled\" ref=\"trailCanvas\" class=\"mouse-trail-canvas\"></canvas></template>")
f.write("<script setup>")
f.write("import { ref, onMounted, onUnmounted, watch } from \"vue\";")
f.write("const props = defineProps({ enabled: { type: Boolean, default: true } });")
f.write("const trailCanvas = ref(null);")
f.write("let ctx = null, particles = [], animationId = null, lastX = 0, lastY = 0;")
f.write("class Particle { constructor(x, y) { this.x = x; this.y = y; this.size = Math.random() * 4 + 2; this.speedX = (Math.random() - 0.5) * 2; this.speedY = (Math.random() - 0.5) * 2; this.opacity = 1; this.decay = Math.random() * 0.02 + 0.015; this.color = [\"rgba(64,158,255,\",\"rgba(103,194,58,\",\"rgba(255,149,0,\",\"rgba(235,64,52,\",\"rgba(155,89,182,\",\"rgba(0,188,212,\",\"rgba(255,235,59,\")[Math.floor(Math.random()*7)]; } update() { this.x += this.speedX; this.y += this.speedY; this.opacity -= this.decay; this.size *= 0.98; } draw(ctx) { ctx.beginPath(); ctx.arc(this.x, this.y, this.size, 0, Math.PI*2); ctx.fillStyle = this.color + this.opacity + \")\"; ctx.fill(); } }")
f.write("function initCanvas() { const canvas = trailCanvas.value; if (!canvas) return; ctx = canvas.getContext(\"2d\"); canvas.width = window.innerWidth; canvas.height = window.innerHeight; }")
f.write("function createParticle(e) { const rect = trailCanvas.value.getBoundingClientRect(); const x = e.clientX - rect.left; const y = e.clientY - rect.top; const dist = Math.sqrt((x-lastX)**2 + (y-lastY)**2); if (dist > 5) { const cnt = Math.min(Math.floor(dist/10), 3); for (let i=0; i<cnt; i++) particles.push(new Particle(lastX + (x-lastX)*(i/cnt), lastY + (y-lastY)*(i/cnt))); } particles.push(new Particle(x, y)); lastX = x; lastY = y; }")
f.write("function animate() { if (!ctx || !trailCanvas.value) return; ctx.clearRect(0,0,trailCanvas.value.width,trailCanvas.value.height); particles = particles.filter(p => p.opacity > 0); particles.forEach(p => { p.update(); p.draw(ctx); }); animationId = requestAnimationFrame(animate); }")
f.write("function handleMouseMove(e) { if (!props.enabled) return; createParticle(e); }")
f.write("watch(() => props.enabled, (v) => { if (v) { initCanvas(); animate(); } else { if (animationId) { cancelAnimationFrame(animationId); animationId = null; } particles = []; } });")
f.write("onMounted(() => { if (props.enabled) { initCanvas(); animate(); } window.addEventListener(\"resize\", () => { if (trailCanvas.value) { trailCanvas.value.width = window.innerWidth; trailCanvas.value.height = window.innerHeight; } }); window.addEventListener(\"mousemove\", handleMouseMove); });")
f.write("onUnmounted(() => { if (animationId) cancelAnimationFrame(animationId); window.removeEventListener(\"mousemove\", handleMouseMove); });")
f.write("</script>")
f.write("<style scoped>.mouse-trail-canvas { position: fixed; top: 0; left: 0; width: 100vw; height: 100vh; pointer-events: none; z-index: 9999; }</style>")
f.close()
